language: erlang
otp_release:
   - 17.4
   - 17.3
   - 17.1
   - 17.0
   - R16B03-1
#   - R16B03 not supported
   - R16B02
   - R16B01
   - R16B
   - R15B03
   - R15B02
   - R15B01
   - R15B

script:
  - make
  - make test
notifications:
  email: false
